package typescript

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/peacewalker122/mapper/ir"
)

// Options controls TypeScript output.
type Options struct {
	// ImportFrom is the module specifier for the Schema type.
	// Default "@mapper/client". Empty means emit standalone types.
	ImportFrom string
	// WithSchema controls whether the Schema const is emitted. Default true.
	WithSchema bool
}

func (o Options) withImport() string {
	return strings.TrimSpace(o.ImportFrom)
}

func pascalCase(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			b.WriteString(p[1:])
		}
	}
	if b.Len() == 0 {
		return "Model"
	}
	return b.String()
}

func camelCase(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for i, p := range parts {
		if p == "" {
			continue
		}
		if i == 0 {
			b.WriteString(p)
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			b.WriteString(p[1:])
		}
	}
	if b.Len() == 0 {
		return "field"
	}
	return b.String()
}

func tsBaseType(ft ir.FieldType) (string, error) {
	switch ft {
	case ir.TypeString, ir.TypeDateTime:
		return "string", nil
	case ir.TypeInteger, ir.TypeDecimal:
		return "number", nil
	case ir.TypeBoolean:
		return "boolean", nil
	default:
		return "", fmt.Errorf("unsupported field type %q", string(ft))
	}
}

func tsFieldType(ft ir.FieldType, required bool) (string, error) {
	base, err := tsBaseType(ft)
	if err != nil {
		return "", err
	}
	if required {
		return base, nil
	}
	return base + " | null", nil
}

// Generate renders a single <model>.gen.ts file.
func Generate(schema ir.Schema, opts Options) ([]byte, error) {
	if strings.TrimSpace(schema.Model.Name) == "" {
		return nil, fmt.Errorf("model name is empty")
	}
	optsImport := opts.withImport()
	structName := pascalCase(schema.Model.Name)
	schemaVar := structName + "Schema"

	var b strings.Builder
	b.WriteString("// Code generated by mapper-gen. DO NOT EDIT.\n\n")
	if optsImport != "" {
		b.WriteString("import type { Schema } from ")
		b.WriteString(strconv.Quote(optsImport))
		b.WriteString(";\n\n")
	} else {
		b.WriteString("export type FieldType = \"string\" | \"integer\" | \"decimal\" | \"boolean\" | \"datetime\";\n\n")
		b.WriteString("export interface SchemaField {\n  id: number;\n  name: string;\n  type: FieldType;\n  required: boolean;\n}\n\n")
		b.WriteString("export interface Schema {\n  id: number;\n  name: string;\n  fields: SchemaField[];\n}\n\n")
	}

	b.WriteString("export interface ")
	b.WriteString(structName)
	b.WriteString(" {\n")
	for _, f := range schema.Model.Fields {
		tsType, err := tsFieldType(f.Type, f.Required)
		if err != nil {
			return nil, err
		}
		prop := camelCase(f.Name)
		b.WriteString("  ")
		b.WriteString(prop)
		if !f.Required {
			b.WriteString("?")
		}
		b.WriteString(": ")
		b.WriteString(tsType)
		b.WriteString(";\n")
	}
	b.WriteString("}\n")

	if opts.WithSchema {
		b.WriteString("\nexport const ")
		b.WriteString(schemaVar)
		b.WriteString(": Schema = {\n")
		b.WriteString("  id: ")
		b.WriteString(strconv.FormatUint(schema.Model.ID, 10))
		b.WriteString(",\n  name: ")
		b.WriteString(strconv.Quote(schema.Model.Name))
		b.WriteString(",\n  fields: [\n")
		for _, f := range schema.Model.Fields {
			if _, err := tsBaseType(f.Type); err != nil {
				return nil, err
			}
			b.WriteString("    { id: ")
			b.WriteString(strconv.FormatUint(f.ID, 10))
			b.WriteString(", name: ")
			b.WriteString(strconv.Quote(f.Name))
			b.WriteString(", type: ")
			b.WriteString(strconv.Quote(string(f.Type)))
			b.WriteString(", required: ")
			b.WriteString(strconv.FormatBool(f.Required))
			b.WriteString(" },\n")
		}
		b.WriteString("  ],\n};\n")
	}

	return []byte(b.String()), nil
}
