package typescript

import (
	"strings"
	"testing"

	"github.com/peacewalker122/mapper/ir"
)

func testSchema() ir.Schema {
	return ir.Schema{
		Version: 1,
		Model: ir.Model{
			ID:   1001,
			Name: "subscriber",
			Fields: []ir.Field{
				{ID: 1002, Name: "msisdn", Type: ir.TypeString, Required: true},
				{ID: 1003, Name: "status", Type: ir.TypeString, Required: true},
				{ID: 1004, Name: "category", Type: ir.TypeString},
				{ID: 1005, Name: "last_tx", Type: ir.TypeDateTime},
				{ID: 1006, Name: "balance", Type: ir.TypeDecimal},
				{ID: 1007, Name: "active", Type: ir.TypeBoolean},
				{ID: 1008, Name: "retries", Type: ir.TypeInteger, Required: true},
			},
		},
	}
}

func TestGenerateProducesTypedModelAndSchema(t *testing.T) {
	generated, err := Generate(testSchema(), Options{ImportFrom: "@mapper/client", WithSchema: true})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	for _, want := range []string{
		"Code generated by mapper-gen",
		`import type { Schema } from "@mapper/client"`,
		"export interface Subscriber",
		"msisdn: string;",
		"status: string;",
		"category?: string | null;",
		"lastTx?: string | null;",
		"balance?: number | null;",
		"active?: boolean | null;",
		"retries: number;",
		"export const SubscriberSchema: Schema",
		"id: 1001",
		`name: "subscriber"`,
		`{ id: 1002, name: "msisdn", type: "string", required: true }`,
		`{ id: 1005, name: "last_tx", type: "datetime", required: false }`,
	} {
		if !strings.Contains(string(generated), want) {
			t.Fatalf("generated TS missing %q:\n%s", want, generated)
		}
	}
}

func TestGenerateStandaloneOmitsImport(t *testing.T) {
	generated, err := Generate(testSchema(), Options{ImportFrom: "", WithSchema: true})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if strings.Contains(string(generated), "@mapper/client") {
		t.Fatalf("standalone output should not reference @mapper/client:\n%s", generated)
	}
	if !strings.Contains(string(generated), "export interface Schema {") {
		t.Fatalf("standalone output should declare Schema:\n%s", generated)
	}
}

func TestGenerateWithoutSchema(t *testing.T) {
	generated, err := Generate(testSchema(), Options{ImportFrom: "@mapper/client"})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if strings.Contains(string(generated), "SubscriberSchema") {
		t.Fatalf("output without schema should omit schema const:\n%s", generated)
	}
	if !strings.Contains(string(generated), "export interface Subscriber") {
		t.Fatalf("output without schema should keep interface:\n%s", generated)
	}
}

func TestGenerateRejectsUnsupportedType(t *testing.T) {
	schema := testSchema()
	schema.Model.Fields[0].Type = ir.FieldType("uuid")
	if _, err := Generate(schema, Options{ImportFrom: "@mapper/client", WithSchema: true}); err == nil {
		t.Fatal("Generate should reject unsupported field type")
	}
}
