package golang

import (
	"go/format"
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/peacewalker122/mapper/ir"
)

func TestGenerateProducesTypedModelAndSchema(t *testing.T) {
	generated, err := Generate(ir.Schema{
		Version: 1,
		Model: ir.Model{
			ID:   1001,
			Name: "subscriber",
			Fields: []ir.Field{
				{ID: 1002, Name: "msisdn", Type: ir.TypeString, Required: true},
				{ID: 1003, Name: "last_tx", Type: ir.TypeDateTime},
			},
		},
	}, "mapping")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "generated.go", generated, parser.AllErrors); err != nil {
		t.Fatalf("generated Go does not parse: %v", err)
	}
	if _, err := format.Source(generated); err != nil {
		t.Fatalf("generated Go does not format: %v", err)
	}
	for _, want := range []string{
		"package mapping",
		"Msisdn string",
		"LastTx *time.Time",
		"SubscriberSchema",
		"ID:       1002",
		"Code generated by mapper-gen",
	} {
		if !strings.Contains(string(generated), want) {
			t.Fatalf("generated Go missing %q:\n%s", want, generated)
		}
	}
}
